language: java

jdk:
  - openjdk7
  
install:
#    !!! WARNING: NEVER USE THE mvn -X SWITCH AS IT LOGS THE SECRET KEY ENV VARIABLES !!!

# compile, package and install the cosmo-manager artifacts. note : tests are not run at this point.

   - "mvn install -DskipTests -f travis-pom.xml"

before_script:

# prepare the orchsetrator-all jar. includes all dependencies. for running a full cycle dsl test.

   - "mvn install -Pall -f orchestrator/pom.xml"
   - "mkdir $HOME/cosmo-work"

# install all necessary cosmo management components.

   - "sudo python2.7 vagrant/bootstrap_lxc_manager.py --working_dir=$HOME/cosmo-work --cosmo_version=0.1-SNAPSHOT"

script:

#    !!! WARNING: NEVER USE THE mvn -X SWITCH AS IT LOGS THE SECRET KEY ENV VARIABLES !!!

   # run unit and integration test

   - "mvn verify -f travis-pom.xml"
   
after_success:
  - "test ${TRAVIS_BRANCH} = develop && gem install travis-artifacts"
  - "test ${TRAVIS_BRANCH} = develop && travis-artifacts upload --path $HOME/.m2/repository/org/cloudifysource/cosmo/bootstrapper --target-path travisci"
  - "test ${TRAVIS_BRANCH} = develop && travis-artifacts upload --path $HOME/.m2/repository/org/cloudifysource/cosmo/orchestrator --target-path travisci"
  - "test ${TRAVIS_BRANCH} = develop && travis-artifacts upload --path $HOME/.m2/repository/org/cloudifysource/cosmo/state-cache --target-path travisci"

  # run the python web server example dsl after verify passes

  - "$HOME/cosmo-work/cosmo.sh --dsl=$HOME/vagrant/test/python_webserver/python-webserver.yaml && wget http://10.0.3.5:8888"


env:
 global:
   - "ARTIFACTS_AWS_REGION=us-east-1"
   - "ARTIFACTS_S3_BUCKET=cosmo-snapshot-maven-repository"
   - secure: "ZFXmjFGg7wHA+u/8HmhAop6Y4zRJIHdVPvWrYHN3zlV5MuaG/5Zfr7HTzVyK\nGirLlRK3g0trDNnkNWYbnu4gfP1V7sPxv+G9HcP0Ig1hr13Xlh8u0u0yCFjp\nD/fW8nndIPNNi+7xT6KZMhUt+oNxEA31rY4dIVGoU7oHCebhD5U="
   - secure: "bXHI5aPs5VROGRwm44wPT49YzU8oSJ4Y82sl5SyAg7oalRPHeTdm2tv+cjx5\nxRaw9BW0CMYycbqQl3Bt8BuPfaQKgNpGdweJTFSdDKNB/rH0qnqFdBYLtbL3\nOv0UJp04XGUidfDjzCtS7uhrF5p/UFKewoFGaYuelasZ0wfCKFU="

# Comments:
# 
#  Don't use your direct AWS credentials. Create limited credentials with Amazon IAM. Here are is the relevant group policy for IAM:
#
# 
# {
#   "Version": "2012-10-17",
#   "Statement": [
#     {
#       "Effect": "Allow",
#       "Action": [
#          "s3:GetObject*", "s3:PutObject*", "s3:DeleteObject*"
#       ],
#       "Resource": [ "arn:aws:s3:::cosmo-snapshot-maven-repository/*" ]
#     },
#     {
#       "Effect": "Allow",
#       "Action": [
#          "s3:ListBucket"
#       ],
#       "Resource": [ "arn:aws:s3:::cosmo-snapshot-maven-repository" ]
#     }
#   ]
# }
# 
#  Encrypting Credentials: http://about.travis-ci.org/docs/user/build-configuration/#Secure-environment-variables
#              travis encrypt -r CloudifySource/cosmo-manager ARTIFACTS_AWS_ACCESS_KEY_ID=xxxxx
#              travis encrypt -r CloudifySource/cosmo-manager ARTIFACTS_AWS_SECRET_ACCESS_KEY=xxxxx

#  How to upload travis artifacts:
#      https:# github.com/travis-ci/travis-artifacts
#      http://stackoverflow.com/questions/16406727/how-to-upload-travis-artifacts-to-s3-only-in-develop-branch/16406929?noredirect=1#16406929
#
#  How to find local maven repo: http:# stackoverflow.com/questions/5916157/how-to-get-the-maven-local-repo
#  Do not use mvn -X switch as it exposes the environment variables and exposes the secret key.
